# Generated with codegen (In Terminal use: playwright codegen 
# http://uitestingplayground.com)

# Author - Robert Chapin
# Date Created - 5/11/2022
# This test navigates to the sampleapp and logs in - it was purely 
# generated by codegen except for lines 6 and 7 
def test_codegen(page):
    page.goto("/")

    # Click text=Sample App
    page.locator("text=Sample App").click()
    # expect(page).to_have_url("http://uitestingplayground.com/sampleapp")
    # Click [placeholder="User Name"]
    page.locator("[placeholder=\"User Name\"]").click()
    # Fill [placeholder="User Name"]
    page.locator("[placeholder=\"User Name\"]").fill("Bob")
    # Press Tab
    page.locator("[placeholder=\"User Name\"]").press("Tab")
    # Fill [placeholder="\*\*\*\*\*\*\*\*"]
    page.locator("[placeholder=\"\\*\\*\\*\\*\\*\\*\\*\\*\"]").fill("pwd")
    # Click text=Log In
    page.locator("text=Log In").click()
    # Click text=Welcome, Bob!
    page.locator("text=Welcome, Bob!").click()
    # Click text=Log Out
    page.locator("text=Log Out").click()